/*1*/
db.restaurants.find().pretty()
/*2*/
db.restaurants.find({},{name:1,borough:1,cuisine:1}).pretty()
/*3*/
db.restaurants.find({},{name:1,borough:1,cuisine:1,_id:0}).pretty()
/*4*/
db.restaurants.find({},{name:1,borough:1,"address.zipcode":1,_id:0}).pretty()
/*5*/
db.restaurants.find({borough:'Bronx'},{name:1,borough:1,cuisine:1}).pretty()
/*6*/
db.restaurants.find({borough:'Bronx'}).limit(5).pretty()
/*7*/
db.restaurants.find({borough:'Bronx'}).skip(5).limit(5).pretty()
/*8*/
db.restaurants.find({"grades.score":{$gt:90}}).pretty()
/*9*/
db.restaurants.find({"grades.score":{$gt:80,$lt:100}}).pretty()
/*10*/
db.restaurants.find({"address.coord.0":{$lt:-95.754168}}).pretty()
/*11*/
db.restaurants.find({$and:[{"grades.score":{$gt:70}},{"address.coord.0":{$lt:-65.754168}},{cuisine:{$ne:"American"}}]}).pretty()
/*12*/
db.restaurants.find({cuisine:{$ne:"American"},"grades.score":{$gt:70},"address.coord.0":{$lt:-65.754168}}).pretty()
/*13*/
db.restaurants.find({cuisine:{$ne:"American"},name:{$ne:"Brooklyn"},"grades.grade":{$eq:"A"}}).sort({cuisine:-1}).pretty()
/*14*/
db.restaurants.find({name:{$regex:"^Wil"}},{name:1,borough:1,cuisine:1}).pretty()
/*15*/
db.restaurants.find({name:{$regex:"^ces"}},{name:1,borough:1,cuisine:1}).pretty()
/*16*/
db.restaurants.find({name:{$regex:"Reg"}},{name:1,borough:1,cuisine:1}).pretty()
/*17*/
db.restaurants.find({borough: {$eq:"Bronx"},cuisine:{$in:["American ","Chinese"]}}).pretty()
/*18*/
db.restaurants.find({borough:{$in:["Staten Island","Queens","Bronx","Brooklyn"]}},{name:1,borough:1,cuisine:1}).pretty()
/*19*/
db.restaurants.find({borough:{$nin:["Staten Island","Queens","Bronx","Brooklyn"]}},{name:1,borough:1,cuisine:1}).pretty()
/*20*/
db.restaurants.find({"grades.score":{$lte:10}},{name:1,borough:1,cuisine:1}).pretty()
/*21*/
db.restaurants.find({$and: [{name:{$regex:"Fish"}},{$or:[{cuisine:{$nin:["American ","Chinese"]}},{name:{$regex:"^Wil"}}]}]},{name:1,borough:1,cuisine:1}).pretty()
/*22*/
db.restaurants.find({"grades.grade":{$eq:"A"},"grades.score":{$eq:11},"grades.date":{$eq:ISODate("2014-08-11T00:00:00")}},{name:1,grades:1}).pretty()
/*23*/
db.restaurants.find({"grades.1.grade":{$eq:"A"},"grades.1.score":{$eq:9},"grades.1.date":{$eq:ISODate("2014-08-11T00:00:00")}},{name:1,grades:1}).pretty()
/*24*/
db.restaurants.find({"address.coord.1":{$gt:42,$lte:52}},{name:1,"address":1}).pretty()
/*25*/
db.restaurants.find().sort({name:1}).pretty()
/*26*/
db.restaurants.find({},{name:1}).sort({name:-1}).pretty()
/*27*/
db.restaurants.find().sort({cuisine:1},{borough:-1}).pretty()
/*28*/
db.restaurants.find({"address.street":{$exists:false}},{name:1, address:1}).pretty()
/*29*/
db.restaurants.find({"address.coord":{$type:"double"}}).pretty()
/*30*/
db.restaurants.find({"grades.score":{$mod:[7,0]}},{name:1,grades:1}).pretty()
/*31*/
db.restaurants.find({name:{$regex:"mon"}},{name:1,borough:1,"address.coord":1,cuisine:1}).pretty()
/*32*/
db.restaurants.find({name:{$regex:"^Man"}},{name:1,borough:1,"address.coord":1,cuisine:1}).pretty()
